### ISSUE TITLE
ns.notifications.onButtonClicked doesn't work outside Chrome

### ISSUE THREAD

**Issue by andreiglingeanu** [lawlietmester/webextension#1]
In your code, you are proxying `onButtonClicked` call just like it is properly implemented in Firefox, which is not.

Do you know if there is any way to emulate that?

https://github.com/lawlietmester/webextension/blob/1e2bada98f7d64fb72e5f3d127df922f76ad3789/browser.js#L704-L715

**Comment by lawlietmester** [comment]
That's correct. I need to remove it from code. As I understand - there is no way to emulate it

**Comment by lawlietmester** [comment]
That's correct - there is no support for FF. As I understand there is no way to emulate it.
