### ISSUE TITLE
Does not work inside Content Script on Firefox

### ISSUE THREAD

**Issue by asgraf** [lawlietmester/webextension#2]
Content Scripts on Firefox have smaller limited set of available apis:
https://developer.mozilla.org/en-US/Add-ons/WebExtensions/Content_scripts#WebExtension_APIs
browser.js causes errors while trying to access methods of APIs outside of this list

**Comment by lawlietmester** [comment]
That's correct. You cannot access other not listed API. If you want to use them - you need to make bridges using onMessage between content script and extension

https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/runtime/sendMessage
https://github.com/mdn/webextensions-examples/tree/master/page-to-extension-messaging

**Comment by asgraf** [comment]
>  If you want to use them

You misunderstood point of my ticket.
No i don't want to use those blaclisted APIs. I wanted to use whitelisted ones via your polyfill.
The simple act of including your polyfill inside content script causes errors, even if you don't call any APIs at all. 
Your polyfill tries to enumerate by all APIs at startup. Even those not existent ones. This causes error inside content script.

**Comment by lawlietmester** [comment]
Please test again with new version. Just tested in firefox - no errors, content scripts are working. Also please provide FF version.

New version is npm based.

`import Browser from 'crossbrowser-webextension';`
